from pptx import Presentation
from pptx.util import Inches
from pptx.util import Pt
import re

def parse_swot_text(text):
    swot_sections = {
        "Core Capabilities": [],
        "Best-Fit Industries": [],
    }

    current_section = None
    buffer = []

    for line in text.splitlines():
        #line = line.strip()
        #line = line.lstrip("* ")
        #line = line.lstrip("# ")
        #line = re.sub(r"^#+\s*", "", line)
        print("line:", line)

        lowered = line.lower()
        is_section = lowered in {"Core Capabilities","Best-Fit Industries"}

        if is_section:
            if current_section and buffer:
                swot_sections[current_section] = buffer[:]
            current_section = line  # Use exact case from the line (e.g., "Strengths")
            buffer = []
            continue

        elif re.match(r"step\s*2", lowered):
            if current_section and buffer:
                swot_sections[current_section] = buffer[:]
            break

        # Clean bullet text
        if current_section and line:
            line = re.sub(r"^[-•\s]*", "", line)
            line = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
            buffer.append(line)

    # Final flush
    if current_section and buffer:
        swot_sections[current_section] = buffer[:]

    return swot_sections


def create_ppt(swot_text, filename="strategy_summary.pptx"):
    prs = Presentation()
    blank_slide_layout = prs.slide_layouts[6]  # blank

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "AI Strategy Summary"
    slide.placeholders[1].text = "Industry Analysis (Generated by AI)"

    # Parse SWOT
    #print("swot_text):", swot_text)
    swot = parse_swot_text(swot_text)
    print("swot:", swot)

    # Add SWOT slide
    slide = prs.slides.add_slide(blank_slide_layout)
    left_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(4.5), Inches(5.5))
    right_box = slide.shapes.add_textbox(Inches(5.0), Inches(0.5), Inches(4.5), Inches(5.5))

    left_frame = left_box.text_frame
    left_frame.word_wrap = True
    left_frame.clear()
    run = left_frame.add_paragraph().add_run()
    run.text = "Core Capabilities"
    run.font.bold = True
    run.font.size = Pt(20)
    run.font.name = "Calibri"
    for point in swot["Core Capabilities"]:
        p = left_frame.add_paragraph()
        run = p.add_run()
        run.text = point
        run.font.size = Pt(12)  # Set font size
        run.font.name = "Calibri"  # Optional: set font type

    right_frame = right_box.text_frame
    right_frame.word_wrap = True
    right_frame.clear()
    run= right_frame.add_paragraph().add_run()
    run.text = "Best-Fit Industries"
    run.font.bold = True
    run.font.size = Pt(20)
    run.font.name = "Calibri"
    for point in swot["Best-Fit Industries"]:
        p = right_frame.add_paragraph()
        run = p.add_run()
        run.text = point
        run.font.size = Pt(12)  # Set font size
        run.font.name = "Calibri"  # Optional: set font type

    prs.save(filename)
    print(f"✅ PowerPoint saved as: {filename}")
